plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.kocumai'
version = '1.0.0'

android {
  namespace "expo.modules.pdfextractor"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
}

repositories {
  mavenCentral()
}

dependencies {
  implementation 'com.tom-roush:pdfbox-android:2.0.27.0'
}
